# Node names
EXTRACT_METADATA = "extract_metadata"
RETRIEVE = "retrieve"
GENERATE = "generate"
FORMAT_OUTPUT = "format_output"
DECIDE_MANUAL_CODE = "decide_manual_code"
RETRIEVE_MANUAL = "retrieve_manual"
RETRIEVE_CODE = "retrieve_code"
GENERATE = "generate"
